name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "autogen/**"
      - "website/**"
      - ".github/workflows/deploy-website.yml"
      - ".github/workflows/docs-check-broken-links.yml"
      - "scripts/broken-links-check.sh"
      - "scripts/docs_build_mkdocs.sh"
      - "scripts/docs_serve_mkdocs.sh"
      - ".muffet-excluded-links.txt"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Step 3: Build MkDocs
      - name: Build documentation
        run: |
          uv venv
          . .venv/bin/activate
          uv pip install -e ".[docs]"
          ./scripts/docs_build_mkdocs.sh
          ls -la ./website/mkdocs/site
        working-directory: .

      # Step 3: Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/mkdocs/site
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy MkDocs site to GitHub pages'
